#!/bin/bash
bucketname=trend-micro-quick-start
version=3.1
url=https://s3.amazonaws.com/${bucketname}/${version}/Common/Scripts/
cd /etc/cfn/
curl -O ${url}createCloudAccount
curl -O ${url}create-console-listener
curl -O ${url}create-console-listener-policy
curl -O ${url}create-DSM-SqlDB.py
curl ${url}reactivate-manager-rh -o reactivate-manager
curl -O ${url}set-aiaSettings
curl -O ${url}set-lbSettings
curl -O ${url}wait-for-relay-and-stop-manager
